# Generated by Django 5.2.1 on 2026-03-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_chat_document_message_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
