# Generated by Django 5.2.1 on 2026-03-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_document_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='display_name',
            field=models.CharField(default='User Doc', max_length=50),
        ),
    ]
